version: '3'

services:

  keycloak:
    image: jboss/keycloak:16.1.1
    #image: sleighzy/keycloak:16.1.0-arm64
    #build:
    #  context: https://github.com/keycloak/keycloak-containers.git#16.1.1:server
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    expose:
      - "8443"
#    ports:
#      - "8443:8443"
    volumes:
      - ./test/keycloak.sh:/opt/jboss/startup-scripts/keycloak.sh

  echo:
    image: solsson/http-echo
    expose:
       - "80"

  apache:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    expose:
      - "443"
#    ports:
#      - "443:443"
    volumes:
      - ./test/valgrind.sh:/tmp/valgrind.sh
      - ./test/openidc.conf:/etc/apache2/conf-available/openidc.conf
    command: ["/tmp/valgrind.sh"]

  jmeter:
    #image: justb4/jmeter
    build: https://github.com/justb4/docker-jmeter.git
    entrypoint: ["/tmp/jmeter.sh"]
    depends_on:
      - keycloak
      - echo
      - apache
    environment:
      THREADS: 5
      LOOP: 5
    volumes:
      - ./test/jmeter.sh:/tmp/jmeter.sh
      - ./test/mod_auth_openidc.jmx:/tmp/mod_auth_openidc.jmx
      - /var/run/docker.sock:/var/run/docker.sock

# docker-compose up --build keycloak apache echo
# docker exec -it `docker ps | grep apache | cut -d" " -f1` tail -f /var/log/apache2/error.log
# docker stop `docker ps | grep apache | cut -d" " -f1`
