blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/zmartzone/mod_auth_openidc/discussions
    about: Please ask and answer questions here.
  - name: Security Vulnerabilities
    url: https://github.com/zmartzone/mod_auth_openidc/security/policy
    about: Please report security vulnerabilities as documented here.