name: Valgrind

on: [push, pull_request]

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          pip3 install docker-compose --upgrade
          docker-compose up --abort-on-container-exit --build
